// Single source of truth for all API paths
// Paths are relative — baseURL in axios adds /api/v1
// To upgrade API version: change VITE_API_URL only

export const API = {
  AUTH: {
    LOGIN:           "/auth/login",
    REGISTER:        "/auth/register",
    FORGOT_PASSWORD: "/auth/forgot-password",
    VERIFY_EMAIL:         "/auth/verify-email",
    RESEND_VERIFICATION:  "/auth/resend-verification",
    DELETE_ACCOUNT:       "/auth/delete-account",
  },
  USER: {
    PROFILE:                   "/user/profile",
    PREFERENCES_AI:            "/user/preferences/ai",
    PREFERENCES_NOTIFICATIONS: "/user/preferences/notifications",
    FEATURE_FLAGS:             "/user/preferences/feature-flags",
    ONBOARDING_PROFILE:        "/user/onboarding/profile",
    ONBOARDING_PREFERENCES:    "/user/onboarding/preferences",
    ONBOARDING_COMPLETE:       "/user/onboarding/complete",
    ONBOARDING_SKIP:           "/user/onboarding/skip",
  },
  ACCOUNT: {
    BASE:                     "/accounts",
    DETAIL:                   (id) => `/accounts/${id}`,
    EA_STATUS:                (id) => `/accounts/${id}/ea/status`,
    EA_GENERATE:              (id) => `/accounts/${id}/ea/generate-key`,
    EA_REVOKE:                (id) => `/accounts/${id}/ea/key`,
    EA_CONFIG:                (id) => `/accounts/${id}/ea/config`,
    RECONCILIATION:           (id) => `/accounts/${id}/reconciliation`,
    ANOMALIES:                (id) => `/accounts/${id}/anomalies`,
    ANOMALY_RESOLVE:          (id, anomalyId) => `/accounts/${id}/anomalies/${anomalyId}`,
    RULES:                    (id) => `/accounts/${id}/rules`,
    RULE:                     (id, ruleId) => `/accounts/${id}/rules/${ruleId}`,
    RULE_TOGGLE:              (id, ruleId) => `/accounts/${id}/rules/${ruleId}/toggle`,
    RULES_EVALUATE:           (id) => `/accounts/${id}/rules/evaluate`,
    PROP_RULES:               (id) => `/accounts/${id}/prop-rules`,
    GRADUATE:                 (id) => `/accounts/${id}/graduate`,
    ACCOUNT_STRATEGIES:       (id) => `/accounts/${id}/strategies`,
    ACCOUNT_STRATEGY:         (id, strategyId) => `/accounts/${id}/strategies/${strategyId}`,
    ACCOUNT_STRATEGY_DEFAULT: (id, strategyId) => `/accounts/${id}/strategies/${strategyId}/default`,
  },
  STRATEGY: {
    BASE:      "/strategies",
    TEMPLATES: "/strategies/templates",
    DETAIL:    (id) => `/strategies/${id}`,
  },
  TRADE: {
    BASE:             "/trades",
    DETAIL:           (id) => `/trades/${id}`,
    STATS_OVERVIEW:   "/trades/stats/overview",
    STATS_PAIRS:      "/trades/stats/pairs",
    STATS_SESSIONS:   "/trades/stats/sessions",
    STATS_WEEKDAYS:   "/trades/stats/weekdays",
    STATS_TIMEFRAMES: "/trades/stats/timeframes",
    STATS_MONTHLY:    "/trades/stats/monthly",
    COMPLIANCE:       (id) => `/trades/${id}/compliance`,
    DISCIPLINE:       (id) => `/trades/${id}/discipline`,
    TAG_STRATEGY:     (id) => `/trades/${id}/strategy`,
  },
  TRANSACTION: {
    BASE:                    "/transactions",
    DETAIL:                  (id) => `/transactions/${id}`,
    REVERSE:                 (id) => `/transactions/${id}/reverse`,
    SUMMARY:                 "/transactions/summary",
    BALANCE_HISTORY:         "/transactions/balance-history",
    ACCOUNT_BALANCE_HISTORY: (id) => `/transactions/account/${id}/balance-history`,
    DISTRIBUTION:            "/transactions/distribution",
    MONTHLY:                 "/transactions/monthly-activity",
  },
  NOTIFICATION: {
    BASE:            "/notifications",
    UNREAD_COUNT:    "/notifications/unread-count",
    READ:            (id) => `/notifications/${id}/read`,
    READ_ALL:        "/notifications/read-all",
    DELETE:          (id) => `/notifications/${id}`,
    PREFERENCES:     "/notifications/preferences",
  },
  IMPORT: {
    PREVIEW:         "/import/preview",
    CONFIRM:         "/import/confirm",
    HISTORY:         "/import/history",
    BATCH:           (id) => `/import/history/${id}`,
    UNDO:            (id) => `/import/history/${id}/undo`,
    TEMPLATE:        "/import/template",
    BROKERS:         "/import/brokers",
    CUSTOM_SCHEMA:   "/import/custom-schema",
  },
  SCORE: {
    ACCOUNT:         (id) => `/score/account/${id}`,
    USER:            "/score/user",
    RECALC_ACCOUNT:  (id) => `/score/account/${id}/recalculate`,
    RECALC_USER:     "/score/user/recalculate",
    HISTORY:         (id) => `/score/account/${id}/history`,
    USER_HISTORY:    "/score/user/history",
  },
  DASHBOARD: {
    OVERVIEW:      "/dashboard/overview",
    PREFERENCES:   "/dashboard/preferences",
    REFRESH_CACHE: (id) => `/dashboard/account/${id}/refresh-cache`,
  },
};
