export const WIDGET_REGISTRY = {
  personal_overview: {
    id:          "personal_overview",
    label:       "Personal Portfolio",
    description: "Your personal trading capital",
    size:        "medium",
    section:     "portfolio",
    icon:        "Wallet",
  },
  prop_overview: {
    id:          "prop_overview",
    label:       "Prop Firm Portfolio",
    description: "Your prop firm accounts",
    size:        "medium",
    section:     "portfolio",
    icon:        "Trophy",
  },
  balance_history: {
    id:          "balance_history",
    label:       "Balance History",
    description: "Your balance over time",
    size:        "large",
    section:     "charts",
    icon:        "TrendingUp",
  },
  win_rate: {
    id:          "win_rate",
    label:       "Win Rate",
    description: "Percentage of winning trades",
    size:        "small",
    section:     "performance",
    icon:        "Target",
  },
  avg_rr: {
    id:          "avg_rr",
    label:       "Avg R:R",
    description: "Average reward to risk ratio",
    size:        "small",
    section:     "performance",
    icon:        "BarChart2",
  },
  streak: {
    id:          "streak",
    label:       "Current Streak",
    description: "Your current winning or losing streak",
    size:        "small",
    section:     "performance",
    icon:        "Zap",
  },
  business_score: {
    id:          "business_score",
    label:       "Business Score",
    description: "Your trading business score",
    size:        "small",
    section:     "score",
    icon:        "Star",
  },
  recent_trades: {
    id:          "recent_trades",
    label:       "Recent Trades",
    description: "Your latest trades",
    size:        "medium",
    section:     "activity",
    icon:        "TrendingUp",
  },
  recent_transactions: {
    id:          "recent_transactions",
    label:       "Recent Transactions",
    description: "Your latest account activity",
    size:        "medium",
    section:     "activity",
    icon:        "ArrowLeftRight",
  },
  pair_performance: {
    id:          "pair_performance",
    label:       "Top Pairs",
    description: "Best performing currency pairs",
    size:        "medium",
    section:     "pairs",
    icon:        "BarChart3",
  },
  prop_challenges: {
    id:          "prop_challenges",
    label:       "Prop Challenges",
    description: "Active prop firm challenges",
    size:        "medium",
    section:     "prop",
    icon:        "Trophy",
  },
  session_performance: {
    id:          "session_performance",
    label:       "Session Performance",
    description: "Performance by trading session",
    size:        "medium",
    section:     "sessions",
    icon:        "Clock",
  },
  weekday_performance: {
    id:          "weekday_performance",
    label:       "Weekday Performance",
    description: "Performance by day of week",
    size:        "medium",
    section:     "sessions",
    icon:        "Calendar",
  },
  monthly_pnl: {
    id:          "monthly_pnl",
    label:       "Monthly P&L",
    description: "P&L by month",
    size:        "medium",
    section:     "charts",
    icon:        "BarChart",
  },
  score_breakdown: {
    id:          "score_breakdown",
    label:       "Score Breakdown",
    description: "Business score pillar details",
    size:        "medium",
    section:     "score",
    icon:        "Star",
  },
  score_history: {
    id:          "score_history",
    label:       "Score History",
    description: "Business score over time",
    size:        "medium",
    section:     "score",
    icon:        "TrendingUp",
  },
};

// Maps widget id → which overview API sections it needs.
// Widgets that self-fetch (session/weekday/monthly/score_history) use []
// so they don't add unnecessary sections to the overview request.
export const WIDGET_SECTIONS_MAP = {
  personal_overview:   ["portfolio"],
  prop_overview:       ["portfolio"],
  balance_history:     ["charts"],
  win_rate:            ["performance"],
  avg_rr:              ["performance"],
  streak:              ["performance"],
  business_score:      ["score"],
  recent_trades:       ["activity"],
  recent_transactions: ["activity"],
  pair_performance:    ["pairs"],
  prop_challenges:     ["portfolio"],
  session_performance: [],
  weekday_performance: [],
  monthly_pnl:         [],
  score_breakdown:     ["score"],
  score_history:       [],
};

export const WIDGET_CATEGORIES = {
  portfolio:   { label: "Portfolio",   ids: ["personal_overview", "prop_overview"] },
  performance: { label: "Performance", ids: ["win_rate", "avg_rr", "streak"] },
  activity:    { label: "Activity",    ids: ["recent_trades", "recent_transactions"] },
  charts:      { label: "Charts",      ids: ["balance_history", "monthly_pnl"] },
  sessions:    { label: "Sessions",    ids: ["session_performance", "weekday_performance"] },
  score:       { label: "Score",       ids: ["business_score", "score_breakdown", "score_history"] },
  pairs:       { label: "Pairs",       ids: ["pair_performance"] },
  prop:        { label: "Prop Firms",  ids: ["prop_challenges"] },
};

export const DEFAULT_WIDGETS = [
  { id: "personal_overview",    enabled: true,  order: 0  },
  { id: "prop_overview",        enabled: true,  order: 1  },
  { id: "win_rate",             enabled: true,  order: 2  },
  { id: "avg_rr",               enabled: true,  order: 3  },
  { id: "streak",               enabled: true,  order: 4  },
  { id: "business_score",       enabled: true,  order: 5  },
  { id: "recent_trades",        enabled: true,  order: 6  },
  { id: "recent_transactions",  enabled: true,  order: 7  },
  { id: "balance_history",      enabled: true,  order: 8  },
  { id: "pair_performance",     enabled: false, order: 9  },
  { id: "prop_challenges",      enabled: true,  order: 10 },
  { id: "session_performance",  enabled: false, order: 11 },
  { id: "weekday_performance",  enabled: false, order: 12 },
  { id: "monthly_pnl",          enabled: false, order: 13 },
  { id: "score_breakdown",      enabled: false, order: 14 },
  { id: "score_history",        enabled: false, order: 15 },
];
